C *******************************************************************
C Parameter Declarations for the IlOGIT Mode Choice Model
C                                Application Program
C
C *******************************************************************

      integer*2    MAX_ZONES,MAX_IZONES,MAX_STATIONS
C ----------------------------------------------------------------
C      GGHM BASIC PARAMETERS
C ----------------------------------------------------------------          
C      parameter(MAX_ZONES     = 3272)
C      parameter(MAX_IZONES    = 3111)
C      parameter(MAX_STATIONS  = 161)
C      parameter(MAX_ZONES     = 3280)
C      parameter(MAX_IZONES    = 3119)
C      parameter(MAX_STATIONS  = 161)
C      parameter(MAX_ZONES     = 3500)
C      parameter(MAX_IZONES    = 3119)
C      parameter(MAX_STATIONS  = 381)
       parameter(MAX_ZONES     = 4000)
       parameter(MAX_IZONES    = 3119)
       parameter(MAX_STATIONS  = 881)